version: "3.7"

services:

  #===============#
  #      PHP      #
  #===============#
  
    php:
     container_name: php
     build:
      context: ./php
      dockerfile: dockerfile
     image: php:latest
     restart: always
     networks:
      - gog-games
     expose:
      - 9000
     volumes:
      - ./html:/usr/share/nginx/html
      
  #===============#
  #    MariaDB    #
  #===============#
  
    mariadb:
     image: yobasystems/alpine-mariadb:latest
     container_name: mariadb
     restart: always
     networks:
      - gog-games
     expose:
      - 3306
     environment:
      - MYSQL_ROOT_PASSWORD=123
     volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
      - ./mariadb:/var/lib/mysql
     depends_on:
      - php

  #===============#
  #   Memcached   #
  #===============#
  
    memcached:
     image: memcached:1.5.16-alpine
     container_name: memcached
     restart: always
     networks:
      - gog-games
     expose:
     - 11211
     depends_on:
      - mariadb
     
  #===============#
  # Elasticsearch #
  #===============#
  
    elasticsearch:
     image: blacktop/elasticsearch:6.6.2
     container_name: elasticsearch
     restart: always
     networks:
      - gog-games
     environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
     ulimits:
      memlock:
       soft: -1
       hard: -1
     volumes:
      - ./elasticsearch:/usr/share/elasticsearch/data
     expose:
      - 9200
     depends_on:
      - memcached

  #===============#
  #     NGINX     #
  #===============#
  
    nginx:
     image: nginx:1.17.0-alpine
     container_name: nginx
     image: nginx:latest
     restart: always
     networks:
      - gog-games
     expose:
      - 80
     volumes: 
      - ./html/:/usr/share/nginx/html/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/site.conf:/etc/nginx/sites-available/site.conf
     depends_on:
      - elasticsearch

  #===============#
  #      Tor      #
  #===============#
  
    tor:
     container_name: tor
     build:
      context: ./tor
      dockerfile: dockerfile
     image: tor:latest
     restart: always
     networks:
      - gog-games
     expose:
      - 9050
     depends_on:
      - nginx  
     volumes:
      - ./tor/private_key:/var/lib/tor/hidden_service/private_key
      
  #===============#
  #    Networks   #
  #===============#
  
networks:
 gog-games:
  driver: bridge